
SRCS =  ../my_lib/lib.c \
		../ex06/ft_list_clear.c \
		ft_list_foreach.c \
		main.c
CC = cc
CFLAG = -Wall -Wextra -Werror

all:
	$(CC) $(CFLAG) $(SRCS) && ./a.out

clean:

fclean: clean
	rm -f *.out

re: fclean all
