SRCS =  ../my_lib/lib.c \
		../ex00/ft_create_elem.c \
		ft_list_push_front.c \
		main.c
CC = cc
CFLAG = -Wall -Wextra -Werror

all:
	$(CC) $(CFLAG) $(SRCS) && ./a.out

clean:

fclean: clean
	rm -f *.out

re: fclean all
