NAME = ft_display_file
SRC = bin/main.c bin/ft_putchar.c bin/ft_putstr.c

all: $(NAME)

$(NAME):
	gcc -Wall -Werror -Wextra -o $(NAME) $(SRC)

clean:
	/bin/rm -f *.o

fclean: clean
	/bin/rm -f $(NAME)